codecov:
  bot: fdominguezclaro
  require_ci_to_pass: true
comment:
  layout: diff, files
  require_changes: true
coverage:
  status:
    patch:
      default:
        informational: false
        target: 100%
    project:
      default:
        informational: false
        target: 100%
